### PR TITLE
Mongoid 4 test

### PR DESCRIPTION
**Pull request by tomg65**
I made this ready for rails 4 with mongoid 4 - works fine in my rails 4 app
Made the fork via an other fork (https://github.com/sebastian-railwaymen)
 - feel free to use this pull.

### CODE REVIEW

**Comment by reedlaw** [comment]
Please merge this, it seems to be working fine for me.

**Comment by dblock** [comment]
Sorry I've missed these PRs, I'd like something clean to merge please, with passing tests, updated CHANGELOG and tests for multiple MongoDB versions (like in https://github.com/dblock/mongoid-scroll) - anyone wants to take it?

**Comment by rocknruby** [comment]
:+1:

**Comment by dblock** [comment]
Bump @tomg65

**Comment by dblock** [comment]
Closing in favor of https://github.com/artsy/mongoid_fulltext/pull/20.

**Pull request closed without merging**
